[2024-04-22T11:42:54.937+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-01T00:00:00+00:00 [queued]>
[2024-04-22T11:42:55.021+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-01T00:00:00+00:00 [queued]>
[2024-04-22T11:42:55.037+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2024-04-22T11:42:55.249+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): second_task> on 2021-08-01 00:00:00+00:00
[2024-04-22T11:42:55.291+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'second_task', 'scheduled__2021-08-01T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp_73spsk_']
[2024-04-22T11:42:55.329+0000] {standard_task_runner.py:88} INFO - Job 20: Subtask second_task
[2024-04-22T11:42:55.281+0000] {standard_task_runner.py:60} INFO - Started process 577 to run task
[2024-04-22T11:42:55.587+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-04-22T11:42:56.025+0000] {task_command.py:423} INFO - Running <TaskInstance: our_first_dag_v5.second_task scheduled__2021-08-01T00:00:00+00:00 [running]> on host 44bc093743d3
[2024-04-22T11:42:56.864+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='our_first_dag_v5' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2021-08-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-08-01T00:00:00+00:00'
[2024-04-22T11:42:56.883+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-22T11:42:56.885+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task2 and will be running after task1!']
[2024-04-22T11:42:56.924+0000] {subprocess.py:86} INFO - Output:
[2024-04-22T11:42:56.934+0000] {subprocess.py:93} INFO - hey, I am task2 and will be running after task1!
[2024-04-22T11:42:56.944+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-22T11:42:57.098+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=second_task, execution_date=20210801T000000, start_date=20240422T114254, end_date=20240422T114257
[2024-04-22T11:42:57.481+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-22T11:42:57.768+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
